- charts/common/templates/deployment.yaml
- charts/common/tests/deployment_test.yaml
Default behaviour will now set `limits.cpu = requests.cpu * 5` and `limits.memory = 1.2 * requests.memory`.
You can override this convention with `container.cpuLimit` and `container.memoryLimit`
Closes #1
> fix: limit 5x cpu, 120% memory, add cpuLimit and memoryLimit

- charts/common/templates/deployment.yaml
- charts/common/templates/hpa.yaml
- charts/common/templates/pdb.yaml
- charts/common/tests/deployment_test.yaml
- charts/common/tests/hpa_test.yaml
- charts/common/tests/pdb_test.yaml
Will enable `forceReplicas: 1` to run with 1 replica in production. The deployment will not have a PDB nor a HPA.
> fix: enable forceReplicas to run with 1 replica in prod

- charts/common/templates/_helpers.tpl
- charts/common/templates/deployment.yaml
- charts/common/tests/deployment_test.yaml
- charts/common/values-ci-tests.yaml
- charts/common/values.yaml
This is a fix #11 PR
Will enable teams to have f.ex:
```yaml
common:
labels:
domain: sales
container:
labels:
version: v1.2.3
```
> fix: enable custom values through common.values closes #11

- charts/common/templates/_helpers.tpl
- charts/common/tests/deployment_test.yaml
This should enable "fixing" throttling for cloudsqlproxy containers without affecting Harness efficiency score
I think this is a correct view for current throttling (ent-kub-prd):
https://grafana-ha.entur.org/explore?left=%7B%22datasource%22:%22prometheus-thanos%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22000000002%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%20by%20(container,%20pod,%20namespace)%20(%5Cn%20%20%20%20rate%20(container_cpu_cfs_throttled_periods_total%7Bcontainer%3D~%5C%22.*proxy.*%5C%22,prometheus_group%3D~%5C%22%5Ekub-ent-prd-001$%5C%22%7D%5B2m%5D)%5Cn%20%20%20%20%20%2F%5Cn%20%20%20%20rate%20(container_cpu_cfs_periods_total%5B2m%5D)%5Cn)%20%3E%200.1%22,%22interval%22:%22%22,%22range%22:true,%22refId%22:%22A%22%7D%5D,%22range%22 …
> feat: Allow setting cloudsqlproxy resource limits via values

- charts/common/README.md
- charts/common/templates/_helpers.tpl
- charts/common/templates/cron.yaml
- charts/common/templates/deployment.yaml
- charts/common/templates/hpa.yaml
- charts/common/templates/ingress.yaml
- charts/common/templates/pdb.yaml
- charts/common/templates/service.yaml
- charts/common/tests/cron_test.yaml
- charts/common/tests/deployment_v1_test.yaml
- charts/common/tests/hpa_test.yaml
- charts/common/tests/ingress_test.yaml
- charts/common/values.yaml
```yaml
deployment:
enabled: false
cron:
enabled: true
schedule: '30 04 * ? *'
containers:
- image: ${artifact.metadata.image}
```
New API: 
```yaml
app: mytest
shortname: mytst
team: team
env: prd
ingress:
host: mytest.dev.entur.io
trafficType: api
service:
ports:
- protocol: TCP
port: 80
targetPort: 8080
pdb:
minAvailable: 25%
hpa:
spec:
metrics:
- type: Resource
resource:
name: cpu
target:
type: Utilization
averageUtilization: 80
behavior:
scaleDown:
stabilizationWindowSeconds: 300
policies:
- type: Pods
value: 1
periodSeconds: 15
scaleUp:
stabilizationWindowSeconds: 60
policies:
- type: Pods
value: 2
periodSeconds: 15
deployment:
replicas: 1
labels:
hello: yes
prometheus:
enabled: true
path: /promhey
port: 999
postgres:
enabled: true
#container:
containers:
- name: ngin1
image: …
```
> feat: multiple ports, multiple deployments, override pdb and hpa

- charts/common/templates/cron.yaml
The CronJob resource refers to the wrong apiVersion. Still trying to figure out how the tests for this resource are able to pass...
> fix: Wrong apiVersion for the CronJob resource

- charts/common/templates/cron.yaml
- charts/common/tests/cron_test.yaml
When trying to use the CronJob resource in the chart, the following error occurs:
```shell
error: error validating "manifests-dry-run.yaml": 
error validating data: [ValidationError(CronJob.spec.jobTemplate.spec): 
unknown field "containers" in io.k8s.api.batch.v1.JobSpec, ValidationError(CronJob.spec.jobTemplate.spec): 
unknown field "restartPolicy" in io.k8s.api.batch.v1.JobSpec, ValidationError(CronJob.spec.jobTemplate.spec): 
unknown field "securityContext" in io.k8s.api.batch.v1.JobSpec, ValidationError(CronJob.spec.jobTemplate.spec): 
unknown field "serviceAccountName" in io.k8s.api.batch.v1.JobSpec, 
ValidationError(CronJob.spec.jobTemplate.spec): missing required field "template" in io.k8s.api.batch.v1.JobSpec]; 
if you choose to ignore these errors, turn validation off with …
```
> fix: Add missing template block in CronJob template

- charts/common/README.md
- charts/common/templates/deployment.yaml
- charts/common/values.yaml
Allowing team tilbud to set maxSurge: 0% to avoid increasing load on existing pods during deployment.
> feat: Add support for setting maxUnavailable and maxSurge for rolling updates

- charts/common/README.md
- charts/common/templates/cron.yaml
- charts/common/templates/deployment.yaml
- charts/common/tests/cron_test.yaml
- charts/common/tests/deployment_test.yaml
- charts/common/values.yaml
This pull request contains two changes:
* It fixes #69 
* It fixes an issue with the CronJob resource where the default value `Always` is [not a permitted value](https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-template) for the `RestartPolicy` field
> feat: Make serviceAccountName overridable for Deployment and CronJob resources

- charts/common/README.md
- charts/common/templates/_helpers.tpl
- charts/common/templates/configmap.yaml
- charts/common/templates/cron.yaml
- charts/common/templates/deployment.yaml
- charts/common/templates/hpa.yaml
- charts/common/templates/ingress.yaml
- charts/common/templates/pdb.yaml
- charts/common/templates/service.yaml
- charts/common/tests/configmap_test.yaml
- charts/common/tests/cron_test.yaml
- charts/common/tests/deployment_test.yaml
- charts/common/tests/hpa_test.yaml
- charts/common/tests/ingress_test.yaml
- charts/common/tests/pdb_test.yaml
- charts/common/tests/service_test.yaml
- charts/common/values.yaml
Enable override of `.Release.Name` with
```yaml
common:
releaseName: my-name
```
Useful for multi-deployment configurations.
> feat: enable releaseName override

- charts/common/README.md
- charts/common/templates/service.yaml
- charts/common/tests/service_test.yaml
- charts/common/values.yaml
Add support for 
```yaml
common:
service:
annotations: 
entur.no/internal-http2: "true"
```
> fix: add annotations to service, needed for internal-http2

- charts/common/README.md
- charts/common/templates/ingress.yaml
- charts/common/tests/ingress_test.yaml
- charts/common/values.yaml
Support adding custom annotations for `Ingress`. 
```
ingress:
...
annotations:
ingress.kubernetes.io/protocol: h2c
```
> feat: option to add custom annotations for ingress

- charts/common/templates/pdb.yaml
- charts/common/tests/pdb_test.yaml
Had an issue for one of the abt-apps for this one.
> fix: For PDB-validation, use replicas from deployment if set.

- charts/common/Chart.yaml
- charts/common/README.md
Point out the presence of `hpa.spec` and `probes.spec`.
@nils1k @Chr1stian @bvestli
> docs: add note about spec override

- charts/common/README.md
- charts/common/templates/_helpers.tpl
- charts/common/tests/deployment_v1_test.yaml
- charts/common/values.yaml
Setting no `cpuLimit` for `postgres:` will not calculate one for you. There no longer is a default `0.3` value.
> fix: allow no `limits.cpu` for postgres

- charts/common/templates/_helpers.tpl
- charts/common/tests/deployment_test.yaml
Ability to set
```yaml
container:
ephemeralStorage: 2Gi
ephemeralStorageLimit: 4Gi
```
Note that unlike `memory` you should name the unit of measure, so instead of 2048, you can do 2Gi
> feat: add ephemeral-storage

- charts/common/templates/_helpers.tpl
- charts/common/tests/cron_test.yaml
- charts/common/tests/deployment_test.yaml
- charts/common/tests/values/common-test-values.yaml
If no `env` is set, chart will force `{}` value.
This will ease migration from custom `env` spec for secrets, to our new `secrets` stanza.
> fix: clear env if not used, cleanup tests

- examples/common/secret-manager-app/README.md
- examples/common/secret-manager-app/values.yaml
> These should be updated so that they reference MNG_AUTH0_INT_CLIENT_ID and MNG_AUTH0_INT_CLIENT_SECRET:
https://github.com/entur/helm-charts/blob/main/examples/common/secret-manager-app/values.yaml#L12-L14 
From: https://github.com/entur/helm-charts/issues/137
> docs: use auth0 name convention [skip ci] (close #137)

- charts/common/templates/_helpers.tpl
- charts/common/templates/deployment.yaml
- charts/common/templates/hpa.yaml
- charts/common/tests/deployment_test.yaml
If HPA is enabled, do not set `replicas` for Deployment.
The `replicas` field is assumed and kept in state so we need
```sh
kubectl apply edit-last-applied # remove replicas
kubectl apply set-last-applied
```
Now, you can deploy again and replicas will not be touched and your HPA will have control over replicas.
> fix: do not set replicas if HPA is enabled

- charts/common/README.md
- charts/common/values.yaml
```yaml
common:
deployments:
- random: stuff
- will: not
- break: me
```
This stanza is not used, removed for clarity.
> docs: remove unused stanza deployments

- charts/common/README.md
- charts/common/templates/deployment.yaml
- charts/common/tests/deployment_test.yaml
- charts/common/values.yaml
Makes it possible to set
```yaml
common:
deployment:
minReadySeconds: 10
```
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#progress-deadline-seconds
> fix: add deployment.minReadySeconds

- charts/common/templates/cron.yaml
- charts/common/tests/cron_test.yaml
- tests/values-cron.yaml
1. Add the labels to the cronjob pods
2. Allow full cronjob schedule syntax (* * * *, or */5 * * * *)
> fix: labels on cronjob pods and schedule fix

- charts/common/templates/deployment.yaml
- charts/common/tests/deployment_test.yaml
If using `deployment.prometheus.enabled` we should still fall back to the default specified for the `container.prometheus` stanza
> fix: inherit prometheus path default from container

- charts/common/README.md
- charts/common/templates/deployment.yaml
- charts/common/tests/deployment_test.yaml
- charts/common/values.yaml
Closes #200 
Adds `initContainers` stanza.
```yaml
common:
app: simple-app
shortname: simapp
team: example
ingress:
trafficType: public
container:
image: myapp:latest
initContainers:
- name: init-app
image: busybox:latest
command: ['sh', '-c', "echo hello"]
```
Will now run `init-app` before starting the container with `myapp:latest`.
> fix: add initContainers
